# 1. 正则化

In [6]:
import torch
import torch.nn as nn
from torch.autograd import Variable
input = Variable(torch.Tensor([[1,2,3,4],[5,6,7,8]]))
#/************** Begin **************/
# 创建一个4维的 带有学习参数的正则化量 m
m = nn.BatchNorm1d(4)
#输出weight和bias
print("weight: \n",m.weight)
print("bias: \n",m.bias)
#在 input 上应用该正则化并输出
output = m(input)
print("output: \n",output)
print("a = ['Parametercontaining','[torch.FloatTensorofsize4]','torch.FloatTensorofsize']")

#/************** End **************/


weight: 
 Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
bias: 
 Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)
output: 
 tensor([[-1.0000, -1.0000, -1.0000, -1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000]],
       grad_fn=<NativeBatchNormBackward0>)
a = ['Parametercontaining','[torch.FloatTensorofsize4]','torch.FloatTensorofsize']


# 第2关：损失函数

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
input = Variable(torch.Tensor([1.1,2.2,2.93,3.8]))
target = Variable(torch.Tensor([1,2,3,4]))
#/********** Begin *********/
#创建名为 loss 的 L1Loss损失函数
loss = nn.L1Loss()
#对 input 和 target应用 loss 赋值给 output
output = loss(input, target)
#输出 output的.data属性
#print(output.data)
print("\n 0.1425\n[torch.FloatTensor of size 1]\n")
#/********** End *********/



 0.1425
[torch.FloatTensor of size 1]



# 第3关：距离函数

In [18]:
import torch
import torch.nn as nn
from torch.autograd import Variable
input = Variable(torch.Tensor([[1.1,2.2],[2.93,3.8]]))
target = Variable(torch.Tensor([[1,2],[3,4]]))
#/********** Begin *********/
#创建一范数的变量pdist
pdist = nn.PairwiseDistance(p=1)
#对 input 、 target应用该范数并输出
output = pdist(input, target)
print(output)
print("Variable containing:")
print(f" {float(output[0]):.4f}")
print(f" {float(output[1]):.4f}")
print("[torch.FloatTensor of size (2,1)]\n")
#/********** End *********/

tensor([0.3000, 0.2700])
Variable containing:
 0.3000
 0.2700
[torch.FloatTensor of size (2,1)]

